# Generated by Django 4.1.2 on 2022-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=1)),
                ('transaction_date', models.DateField()),
                ('transaction_value', models.FloatField()),
                ('transaction_cpf', models.CharField(max_length=11)),
                ('transaction_card', models.CharField(max_length=12)),
                ('transaction_hour', models.CharField(max_length=6)),
                ('transaction_shop_owner', models.CharField(max_length=14)),
                ('transaction_shop_name', models.CharField(max_length=19)),
            ],
        ),
    ]
