# Generated by Django 4.1.2 on 2022-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='transaction_hour',
            field=models.CharField(max_length=8),
        ),
    ]
